# Generated by Django 4.1.7 on 2023-05-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_actor_director_slug_movie_avg_rating_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='films.movie'),
        ),
    ]
